1 dimensional array on numpy

In [1]:
import numpy as np

a=np.array([1,2,3])
print (a)


[1 2 3]


2 dimensional array in numpy

In [2]:
import numpy as np

a=np.array([[1,2],[3,4]])
print (a)

[[1 2]
 [3 4]]


In [3]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


5D Array of numpy

In [4]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)

[[[[[1 2 3 4]]]]]


Check dimesion of array

In [8]:
import numpy as np 
a=np.array(42)
b = np.array([1,2,3,4,5])
print(a.ndim)
print(b.ndim)


0
1


find the shape of array

In [13]:
arr=np.array([[1,3,4,5]])
print(arr.shape)

(1, 4)


Matrix operations helping functions

In [29]:
import numpy as np
print(np.zeros(5))
print(np.ones(5))
print(np.arange(1,4))


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1 2 3]


Sorting Arrays np.sort()

In [30]:
import numpy as np

arr = np.array([2,4,1,5,7,9,8,0,3])
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 7, 8, 9])

Alphabetic sort

In [31]:
arr=np.array(['Banana','Apple','Citrus Fruit','Mango','Grapes'])
np.sort(arr)

array(['Apple', 'Banana', 'Citrus Fruit', 'Grapes', 'Mango'], dtype='<U12')

Access arrays in numpy

In [39]:
import numpy as np
data = np.array([1,2,3])
print(data[0])
print(data[0:2])
print(data[1:])
print(data[:2])

1
[1 2]
[2 3]
[1 2]
